package protocol;

public enum CSReturnValues {
    REGISTRATION_OK,
    LOGIN_OK,
    USERNAME_NOT_PRESENT,
    USERNAME_INVALID,
    USERNAME_ALREADY_PRESENT,
    ALREADY_LOGGED_IN,
    PSW_INCORRECT,
    CREATE_PROJECT_OK,
    PROJECT_ALREADY_PRESENT,
    SERVER_INTERNAL_NETWORK_ERROR,
    LOGOUT_OK;
}
