package protocol;

public enum CSReturnValues {
    REGISTRATION_OK,
    LOGIN_OK,
    LIST_PROJECTS_OK,
    USERNAME_NOT_PRESENT,
    USERNAME_INVALID,
    USERNAME_ALREADY_PRESENT,
    ALREADY_LOGGED_IN,
    PSW_INCORRECT,
    CREATE_PROJECT_OK,
    PROJECT_ALREADY_PRESENT,
    PROJECT_NOT_PRESENT,
    SHOW_PROJECT_OK,
    SHOW_MEMBERS_OK,
    ADD_MEMBER_OK,
    DELETE_PROJECT_OK,
    ILLEGAL_OPERATION,
    MOVE_CARD_OK,
    CARD_FROM_STATUS_OUTDATED,
    ADD_CARD_OK,
    CARD_ALREADY_PRESENT,
    CHAT_STOP,
    SERVER_INTERNAL_NETWORK_ERROR,
    LOGOUT_OK;
}
